image: maven:3.5-jdk-8

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"


stages:
  - build
  - test

job1:
  stage: build
  script:
    - mvn compile

job2:
  stage: test
  script:
    - mvn test
